ativos/urls.py
from django.urls import path

from . import views

app_name = "ativos"
urlpatterns = [
    path("", views.ComputerView.as_view(), name="index"),
    path("inventory/", views.InventoryView.as_view(), name="inventory"),
]

emprestimo/presentation/urls.py
from django.urls import path

from . import views

app_name = "emprestimo"

urlpatterns = [
    path(
        "tipo_ocorrencia/",
        views.ListarTipoOcorrenciaView.as_view(),
        name="listar_tipos_ocorrencia",
    ),
    path(
        "tipo_ocorrencia/add",
        views.CriarTipoOcorrenciaView.as_view(),
        name="criar_tipo_ocorrencia",
    ),
    path(
        "tipo_ocorrencia/change/<int:pk>/",
        views.EditarTipoOcorrenciaView.as_view(),
        name="editar_tipo_ocorrencia",
    ),
    path(
        "tipo_ocorrencia/delete/<int:pk>/",
        views.remover_tipo_ocorrencia,
        name="remover_tipo_ocorrencia",
    ),
    path(
        "emprestimo/",
        views.ListarEmprestimoView.as_view(),
        name="listar_emprestimos",
    ),
    path(
        "emprestimo/<int:pk>",
        views.VisualizarEmprestimoView.as_view(),
        name="visualizar_emprestimo",
    ),
    path(
        "emprestimo/add",
        views.CriarEmprestimoView.as_view(),
        name="criar_emprestimo",
    ),
    path(
        "emprestimo/change/<int:pk>/",
        views.EditarEmprestimoView.as_view(),
        name="editar_emprestimo",
    ),
    path(
        "emprestimo/delete/<int:pk>/",
        views.remover_emprestimo,
        name="remover_emprestimo",
    ),
    path(
        "emprestimo/registrar_devolucao/<int:pk>/",
        views.registrar_devolucao_view,
        name="registrar_devolucao",
    ),
    path(
        "emprestimo/gerar_termo_responsabilidade/<int:pk>/",
        views.gerar_termo_responsabilidade_view,
        name="gerar_termo_responsabilidade",
    ),
    path(
        "emprestimo/gerar_termo_devolucao/<int:pk>/",
        views.gerar_termo_devolucao_view,
        name="gerar_termo_devolucao",
    ),
    path(
        "ocorrencias/", views.ListarOcorrenciasView.as_view(), name="listar_ocorrencias"
    ),
    path(
        "ocorrencias/<int:pk>",
        views.VisualizarOcorrenciaView.as_view(),
        name="visualizar_ocorrencia",
    ),
    path(
        "ocorrencias/aluno/<int:aluno_id>/",
        views.ListarOcorrenciasAlunoView.as_view(),
        name="listar_ocorrencias_aluno",
    ),
    path(
        "ocorrencias/bem/<int:bem_id>/",
        views.ListarOcorrenciasBemView.as_view(),
        name="listar_ocorrencias_bem",
    ),
    path(
        "ocorrencias/emprestimo/<int:emprestimo_id>/",
        views.ListarOcorrenciasEmprestimoView.as_view(),
        name="listar_ocorrencias_emprestimo",
    ),
    path(
        "ocorrencias/registrar/",
        views.RegistrarOcorrenciaView.as_view(),
        name="registrar_ocorrencia",
    ),
    path(
        "ocorrencias/registrar/emprestimo/<int:emprestimo_id>/",
        views.registrar_ocorrencia_ao_emprestimo,
        name="registrar_ocorrencia_ao_emprestimo",
    ),
    path(
        "ocorrencias/cancelar/<int:pk>/",
        views.CancelarOcorrenciaView.as_view(),
        name="cancelar_ocorrencia",
    ),
    path(
        "emprestimo/atualizar_tabela_emprestimo/",
        views.atualizar_tabela_emprestimo_view,
        name="atualizar_tabela_emprestimo",
    ),
]

ensino/presentation/urls.py
from django.urls import path

from . import views


app_name = "ensino"

urlpatterns = [
    path(
        "campus/",
        views.ListarCampusView.as_view(),
        name="listar_campi",
    ),
    path(
        "campus/add",
        views.CriarCampusView.as_view(),
        name="criar_campus",
    ),
    path(
        "campus/change/<int:pk>/",
        views.EditarCampusView.as_view(),
        name="editar_campus",
    ),
    path(
        "campus/delete/<int:pk>/",
        views.remover_campus,
        name="remover_campus",
    ),
    path(
        "curso/",
        views.ListarCursoView.as_view(),
        name="listar_cursos",
    ),
    path(
        "curso/add",
        views.CriarCursoView.as_view(),
        name="criar_curso",
    ),
    path(
        "curso/change/<int:pk>/",
        views.EditarCursoView.as_view(),
        name="editar_curso",
    ),
    path(
        "curso/delete/<int:pk>/",
        views.remover_curso,
        name="remover_curso",
    ),
    path(
        "forma_selecao/",
        views.ListarFormaSelecaoView.as_view(),
        name="listar_formas_selecao",
    ),
    path(
        "forma_selecao/add",
        views.CriarFormaSelecaoView.as_view(),
        name="criar_forma_selecao",
    ),
    path(
        "forma_selecao/change/<int:pk>/",
        views.EditarFormaSelecaoView.as_view(),
        name="editar_forma_selecao",
    ),
    path(
        "forma_selecao/delete/<int:pk>/",
        views.remover_forma_selecao,
        name="remover_forma_selecao",
    ),
    path(
        "aluno/",
        views.ListarAlunoView.as_view(),
        name="listar_alunos",
    ),
    path(
        "aluno/add",
        views.CriarAlunoView.as_view(),
        name="criar_aluno",
    ),
    path(
        "aluno/change/<int:pk>/",
        views.EditarAlunoView.as_view(),
        name="editar_aluno",
    ),
    path(
        "aluno/delete/<int:pk>/",
        views.remover_aluno,
        name="remover_aluno",
    ),
]

inventory_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ativos/', include('ativos.urls')),
]

patrimonio/presentation/urls.py
from django.urls import path

from . import views


app_name = "patrimonio"
urlpatterns = [
    path(
        "tipo_bem/",
        views.ListarTiposBemView.as_view(),
        name="listar_tipos_bem",
    ),
    path(
        "tipo_bem/add",
        views.CriarTipoBemView.as_view(),
        name="criar_tipo_bem",
    ),
    path(
        "tipo_bem/change/<int:pk>/",
        views.EditarTipoBemView.as_view(),
        name="editar_tipo_bem",
    ),
    path(
        "tipo_bem/delete/<int:pk>/",
        views.remover_tipobem,
        name="remover_tipo_bem",
    ),
    path(
        "estado_conservacao/",
        views.ListarEstadosConservacaoView.as_view(),
        name="listar_estados_conservacao",
    ),
    path(
        "estado_conservacao/add",
        views.CriarEstadoConservacaoView.as_view(),
        name="criar_estado_conservacao",
    ),
    path(
        "estado_conservacao/change/<int:pk>/",
        views.EditarEstadoConservacaoView.as_view(),
        name="editar_estado_conservacao",
    ),
    path(
        "estado_conservacao/delete/<int:pk>/",
        views.remover_estado_conservacao,
        name="remover_estado_conservacao",
    ),
    path(
        "grau_fragilidade/",
        views.ListarGrauFragilidadeView.as_view(),
        name="listar_grau_fragilidade",
    ),
    path(
        "grau_fragilidade/add",
        views.CriarGrauFragilidadeView.as_view(),
        name="criar_grau_fragilidade",
    ),
    path(
        "grau_fragilidade/change/<int:pk>/",
        views.EditarGrauFragilidadeView.as_view(),
        name="editar_grau_fragilidade",
    ),
    path(
        "grau_fragilidade/delete/<int:pk>/",
        views.remover_grau_fragilidade,
        name="remover_grau_fragilidade",
    ),
    path(
        "marca_modelo/",
        views.ListarMarcaModeloView.as_view(),
        name="listar_marca_modelo",
    ),
    path(
        "marca_modelo/add",
        views.CriarMarcaModeloView.as_view(),
        name="criar_marca_modelo",
    ),
    path(
        "marca_modelo/change/<int:pk>/",
        views.EditarMarcaModeloView.as_view(),
        name="editar_marca_modelo",
    ),
    path(
        "marca_modelo/delete/<int:pk>/",
        views.remover_marca_modelo,
        name="remover_marca_modelo",
    ),
    path(
        "bem/",
        views.ListarBemView.as_view(),
        name="listar_bens",
    ),
    path(
        "bem/add",
        views.CriarBemView.as_view(),
        name="criar_bem",
    ),
    path(
        "bem/change/<int:pk>/",
        views.EditarBemView.as_view(),
        name="editar_bem",
    ),
    path(
        "bem/delete/<int:pk>/",
        views.remover_bem,
        name="remover_bem",
    ),
]

sigecomp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ativos/", include("ativos.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

sigemp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.presentation.views import model_autocomplete

urlpatterns = [
    path("", include("core.presentation.urls")),
    path("patrimonio/", include("patrimonio.presentation.urls")),
    path("ensino/", include("ensino.presentation.urls")),
    path("emprestimo/", include("emprestimo.presentation.urls")),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/reset_done.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "accounts/password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "autocomplete/",
        model_autocomplete,
        name="model_autocomplete",
    ),
]

core/presentation/forms.py
from django.forms import CharField, Form, PasswordInput


class LoginForm(Form):
    username = CharField(label="Usuário", max_length=100, required=True)
    password = CharField(
        label="Senha", max_length=100, widget=PasswordInput, required=True
    )

core/presentation/views.py
from datetime import timedelta
from django.contrib import messages
from django.contrib.auth import login, logout
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.http.request import HttpRequest
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_not_required, login_required
from django.urls import reverse
from django.utils import timezone
from django.template.loader import render_to_string
from django.views.decorators.http import require_GET
from django.apps import apps
from core.presentation.forms import LoginForm
from core.repositories.django import DjUserRepository
from core.usecases import login_usecase

from emprestimo.domain.types import EmprestimoEstadoEnum
from emprestimo.models import Emprestimo, Ocorrencia
from emprestimo.policies.django import DjangoEmprestimoPolicy
from ensino.models import Aluno
from patrimonio.models import Bem, EstadoConservacao


# Create your views here.
@login_not_required
def login_view(request: HttpRequest):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            repo = DjUserRepository()

            result = login_usecase(
                form.cleaned_data["username"],
                form.cleaned_data["password"],
                repo,
            )

            if not result:
                messages.error(request, result.mensagem)
                return redirect(reverse("core:login"))

            user: User = result.value
            login(request, user)
            return redirect(reverse("core:home"))

    return render(request, "registration/login.html", {"form": LoginForm})


def home_view(request: HttpRequest):
    count_emprestimos_ativos: int = Emprestimo.objects.filter(
        estado=EmprestimoEstadoEnum.ATIVO
    ).count()

    count_emprestimos_vencendo: int = Emprestimo.objects.filter(
        data_devolucao_prevista=timezone.now()
    ).count()

    emprestimos_recentes = Emprestimo.objects.filter(
        data_emprestimo__gt=timezone.now() - timedelta(days=14),
        estado=EmprestimoEstadoEnum.ATIVO,
    ).order_by("-data_emprestimo")[:3]

    count_alunos = Aluno.objects.all().count()

    count_novos_alunos = Aluno.objects.filter(
        criado_em__gt=timezone.now() - timedelta(days=30)
    ).count()

    count_bens_disponiveis = (
        Bem.objects.exclude(emprestimo__estado=EmprestimoEstadoEnum.ATIVO)
        .distinct()
        .count()
    )

    count_bens_com_ocorrencias = (
        Bem.objects.filter(
            emprestimo__ocorrencia__isnull=False,
            emprestimo__estado=EmprestimoEstadoEnum.ATIVO,
        )
        .distinct()
        .count()
    )

    count_ocorrencias = Ocorrencia.objects.filter(cancelado_em__isnull=True).count()

    emprestimo_policy = DjangoEmprestimoPolicy(request.user)

    pode_criar_emprestimo = emprestimo_policy.pode_criar()

    context = {
        "count_emprestimos_ativos": count_emprestimos_ativos,
        "count_emprestimos_vencendo": count_emprestimos_vencendo,
        "emprestimos_recentes": emprestimos_recentes,
        "count_alunos": count_alunos,
        "count_novos_alunos": count_novos_alunos,
        "count_bens_disponiveis": count_bens_disponiveis,
        "count_bens_com_ocorrencias": count_bens_com_ocorrencias,
        "count_ocorrencias": count_ocorrencias,
        "pode_criar_emprestimo": pode_criar_emprestimo,
    }

    return render(request, "core/home.html", context=context)


def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse("core:login"))


@require_GET
def model_autocomplete(request):
    q = request.GET.get("q", "").strip()
    app_label = request.GET.get("app_label")
    model_name = request.GET.get("model_name")
    field = request.GET.get("field", "__str__")
    limit = int(request.GET.get("limit", 10))

    if not (app_label and model_name):
        return HttpResponseBadRequest("Missing parameters.")

    Model = apps.get_model(app_label, model_name)
    if Model is None:
        return HttpResponseBadRequest("Invalid model.")

    if not q:
        qs = Model.objects.none()
    elif field != "__str__":
        if field not in [f.name for f in Model._meta.get_fields()]:
            return HttpResponseBadRequest("Invalid field.")
        filter_kwargs = {f"{field}__icontains": q}
        qs = Model.objects.filter(**filter_kwargs)[:limit]
    else:
        all_objects = Model.objects.all()
        qs = [obj for obj in all_objects if q.lower() in str(obj).lower()][:limit]

    if request.headers.get("HX-Request"):
        html = render_to_string(
            "partials/autocomplete_results.html",
            {"results": qs, "field": field},
            request=request,
        )
        return HttpResponse(html)
    else:
        data = {
            "results": [
                {
                    "id": str(obj.pk),
                    "text": str(obj) if field == "__str__" else getattr(obj, field, ""),
                    "value": str(obj.pk),
                }
                for obj in qs
            ]
        }
        return JsonResponse(data)

core/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_not_required
from django.http.request import HttpRequest
from django.shortcuts import redirect, render
from django.contrib.auth.models import User

from core.forms import LoginForm
from core.usecases import login_usecase


# Create your views here.
def login_view(request: HttpRequest):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            repo = DjUserRepository()
            result = login_usecase(
                form.cleaned_data["username"],
                form.cleaned_data["password"],
                repo,
            )

            if not result:
                messages.error(request, "Usuario ou senha incorretos.")
                return redirect("login")

            user: User = result.data
            login(request, user)
            return redirect("home")

    return render(request, "registration/login.html", {"form": LoginForm})

core/templates/core/home.html
{% extends "base.html" %}
{% block page_title %}
    Painel
{% endblock page_title %}
{% block actions %}
    {% if pode_criar_emprestimo %}
        <div class="flex justify-end md:justify-start">
            <a href="{% url 'emprestimo:criar_emprestimo' %}">
                <div class="rounded-md py-2 gap-2 flex px-4 border border-blue-500 text-blue-600 dark:border-blue-400 dark:text-blue-300 bg-blue-50 dark:bg-gray-800 items-center font-semibold text-sm transition-all duration-300 ease-in-out hover:bg-blue-100 dark:hover:bg-gray-700 hover:ring-2 hover:ring-blue-300 dark:hover:ring-blue-500/40 hover:shadow-md cursor-pointer">
                    <i class="material-symbols-outlined transition-transform duration-300 group-hover:rotate-6">add</i>
                    <span class="hidden md:block">Novo Empréstimo</span>
                </div>
            </a>
        </div>
    {% endif %}
{% endblock actions %}
{% block content %}
    <section class="mx-auto mb-6 grid max-w-7xl grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
        <a href="{% url 'emprestimo:listar_emprestimos' %}"
           class="group flex flex-row justify-between rounded-md bg-gray-50 p-6 text-gray-900 shadow-md transition-all duration-300 hover:scale-105 hover:shadow-xl dark:bg-gray-900 dark:text-gray-200 max-h-36 border border-transparent hover:border-green-200 dark:hover:border-green-800">
            <div class="flex flex-col p-2">
                <p class="text-gray-700 dark:text-gray-300 text-nowrap">Empréstimos Ativos</p>
                <p class="text-xl">{{ count_emprestimos_ativos }}</p>
                <p class="text-xs text-gray-500 dark:text-gray-300">{{ count_emprestimos_vencendo }} Vencendo hoje</p>
            </div>
            <div class="flex justify-center items-center">
                <div class="bg-green-500 text-white rounded-full p-3 h-16 w-16 shadow-lg transition-transform group-hover:scale-110">
                    <i class="material-symbols-outlined text-center text-4xl align-middle">contract</i>
                </div>
            </div>
        </a>
        <a href="{% url 'ensino:listar_alunos' %}"
           class="group flex flex-row justify-between rounded-md bg-gray-50 p-6 text-gray-900 shadow-md transition-all duration-300 hover:scale-105 hover:shadow-xl dark:bg-gray-900 dark:text-gray-200 max-h-36 border border-transparent hover:border-cyan-200 dark:hover:border-cyan-800">
            <div class="flex flex-col p-2">
                <p class="text-gray-700 dark:text-gray-300">Total de alunos</p>
                <p class="text-xl">{{ count_alunos }}</p>
                <p class="text-xs text-gray-500 dark:text-gray-300">{{ count_novos_alunos }} novos esse mês</p>
            </div>
            <div class="flex justify-center items-center">
                <div class="bg-cyan-500 text-white rounded-full p-3 h-16 w-16 shadow-lg transition-transform group-hover:scale-110">
                    <i class="material-symbols-outlined text-center text-4xl align-middle">group</i>
                </div>
            </div>
        </a>
        <a href="{% url 'patrimonio:listar_bens' %}"
           class="group flex flex-row justify-between rounded-md bg-gray-50 p-6 text-gray-900 shadow-md transition-all duration-300 hover:scale-105 hover:shadow-xl dark:bg-gray-900 dark:text-gray-200 max-h-36 border border-transparent hover:border-purple-200 dark:hover:border-purple-800">
            <div class="flex flex-col p-2">
                <p class="text-gray-700 dark:text-gray-300">Bens Disponíveis</p>
                <p class="text-xl">{{ count_bens_disponiveis }}</p>
                <p class="text-xs text-gray-500 dark:text-gray-300">{{ count_bens_com_ocorrencias }} com ocorrências</p>
            </div>
            <div class="flex justify-center items-center">
                <div class="bg-purple-500 text-white rounded-full p-3 h-16 w-16 shadow-lg transition-transform group-hover:scale-110">
                    <i class="material-symbols-outlined text-center text-4xl align-middle">package</i>
                </div>
            </div>
        </a>
        <a href="{% url 'emprestimo:listar_ocorrencias' %}"
           class="group flex flex-row justify-between rounded-md bg-gray-50 p-6 text-gray-900 shadow-md transition-all duration-300 hover:scale-105 hover:shadow-xl dark:bg-gray-900 dark:text-gray-200 max-h-36 border border-transparent hover:border-orange-200 dark:hover:border-orange-800">
            <div class="flex flex-col p-2">
                <p class="text-gray-700 dark:text-gray-300">Ocorrências</p>
                <p class="text-xl">{{ count_ocorrencias }}</p>
                <p class="text-xs text-gray-500 dark:text-gray-300">Pendentes de resolução</p>
            </div>
            <div class="flex justify-center items-center">
                <div class="bg-orange-500 text-white rounded-full p-3 h-16 w-16 shadow-lg transition-transform group-hover:scale-110">
                    <i class="material-symbols-outlined text-center text-4xl align-middle">exclamation</i>
                </div>
            </div>
        </a>
    </section>
    <section class="mx-auto max-w-7xl rounded-md bg-gray-50 p-4 text-gray-500 shadow-md dark:bg-gray-900 dark:text-gray-300">
        <div class="flex flex-row justify-between items-center mb-4">
            <div class="font-medium text-lg text-gray-900 dark:text-gray-200">Emprestimos recentes</div>
            <a href="{% url 'emprestimo:listar_emprestimos' %}"
               class="cursor-pointer flex items-center gap-2 rounded-lg border border-gray-200 bg-gray-50 px-4 py-2 text-sm font-medium text-gray-600 transition-all duration-300 ease-in-out hover:bg-gray-100 hover:shadow-md hover:ring-2 hover:ring-gray-300 dark:border-gray-400 dark:bg-gray-900/20 dark:text-gray-300 hover:dark:bg-gray-900/30 dark:hover:ring-gray-500/40">
                <i class="material-symbols-outlined align-middle text-base">contract</i>
                <span class="hidden md:block">Ver todos</span>
            </a>
        </div>
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
            {% for emprestimo in emprestimos_recentes %}
                <a href="{% url 'emprestimo:visualizar_emprestimo' emprestimo.id %}"
                   class="group flex flex-col rounded-md bg-gray-50 p-6 gap-2 border border-gray-200 text-gray-900 shadow-md transition-all duration-300 hover:scale-105 hover:shadow-lg hover:border-green-200 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200">
                    <div class="flex flex-row justify-between">
                        <span class="text-gray-700 group-hover:text-green-600 transition-colors duration-200 dark:text-gray-300 dark:group-hover:text-green-400 font-medium">#{{ emprestimo.id }}</span>
                        <span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium {% if emprestimo.estado == 1 %} bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300 {% elif emprestimo.estado == 2 %} bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300  {% else %} bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300 {% endif %}">
                            {{ emprestimo.get_estado_display }}
                        </span>
                    </div>
                    <div class="text-sm text-gray-700 dark:text-gray-300">
                        <p class="flex items-center gap-1">
                            <i class="material-symbols-outlined align-middle text-base">person</i>
                            <span>{{ emprestimo.aluno.nome }}</span>
                        </p>
                        <p class="flex items-center gap-1">
                            <i class="material-symbols-outlined align-middle text-base">inventory_2</i>
                            <span>{{ emprestimo.bem.descricao }}</span>
                        </p>
                        <p class="flex items-center gap-1">
                            <i class="material-symbols-outlined align-middle text-base">calendar_month</i>
                            <span>{{ emprestimo.data_emprestimo|date:"d/m/Y" }} -
                                {% if data_devolucao %}
                                    {{ emprestimo.data_devolucao|date:"d/m/Y" }}
                                {% else %}
                                    {{ emprestimo.data_devolucao_prevista|date:"d/m/Y" }}
                                {% endif %}
                            </span>
                        </p>
                    </div>
                </a>
            {% endfor %}
        </div>
    </section>
{% endblock %}