ativos/urls.py
from django.urls import path

from . import views

app_name = "ativos"
urlpatterns = [
    path("", views.ComputerView.as_view(), name="index"),
    path("inventory/", views.InventoryView.as_view(), name="inventory"),
]

emprestimo/presentation/urls.py
from django.urls import path

from . import views

app_name = "emprestimo"

urlpatterns = [
    path(
        "tipo_ocorrencia/",
        views.ListarTipoOcorrenciaView.as_view(),
        name="listar_tipos_ocorrencia",
    ),
    path(
        "tipo_ocorrencia/add",
        views.CriarTipoOcorrenciaView.as_view(),
        name="criar_tipo_ocorrencia",
    ),
    path(
        "tipo_ocorrencia/change/<int:pk>/",
        views.EditarTipoOcorrenciaView.as_view(),
        name="editar_tipo_ocorrencia",
    ),
    path(
        "tipo_ocorrencia/delete/<int:pk>/",
        views.remover_tipo_ocorrencia,
        name="remover_tipo_ocorrencia",
    ),
    path(
        "emprestimo/",
        views.ListarEmprestimoView.as_view(),
        name="listar_emprestimos",
    ),
    path(
        "emprestimo/<int:pk>",
        views.VisualizarEmprestimoView.as_view(),
        name="visualizar_emprestimo",
    ),
    path(
        "emprestimo/add",
        views.CriarEmprestimoView.as_view(),
        name="criar_emprestimo",
    ),
    path(
        "emprestimo/change/<int:pk>/",
        views.EditarEmprestimoView.as_view(),
        name="editar_emprestimo",
    ),
    path(
        "emprestimo/delete/<int:pk>/",
        views.remover_emprestimo,
        name="remover_emprestimo",
    ),
    path(
        "emprestimo/registrar_devolucao/<int:pk>/",
        views.registrar_devolucao_view,
        name="registrar_devolucao",
    ),
    path(
        "emprestimo/gerar_termo_responsabilidade/<int:pk>/",
        views.gerar_termo_responsabilidade_view,
        name="gerar_termo_responsabilidade",
    ),
    path(
        "emprestimo/gerar_termo_devolucao/<int:pk>/",
        views.gerar_termo_devolucao_view,
        name="gerar_termo_devolucao",
    ),
    path(
        "ocorrencias/", views.ListarOcorrenciasView.as_view(), name="listar_ocorrencias"
    ),
    path(
        "ocorrencias/<int:pk>",
        views.VisualizarOcorrenciaView.as_view(),
        name="visualizar_ocorrencia",
    ),
    path(
        "ocorrencias/aluno/<int:aluno_id>/",
        views.ListarOcorrenciasAlunoView.as_view(),
        name="listar_ocorrencias_aluno",
    ),
    path(
        "ocorrencias/bem/<int:bem_id>/",
        views.ListarOcorrenciasBemView.as_view(),
        name="listar_ocorrencias_bem",
    ),
    path(
        "ocorrencias/emprestimo/<int:emprestimo_id>/",
        views.ListarOcorrenciasEmprestimoView.as_view(),
        name="listar_ocorrencias_emprestimo",
    ),
    path(
        "ocorrencias/registrar/",
        views.RegistrarOcorrenciaView.as_view(),
        name="registrar_ocorrencia",
    ),
    path(
        "ocorrencias/registrar/emprestimo/<int:emprestimo_id>/",
        views.registrar_ocorrencia_ao_emprestimo,
        name="registrar_ocorrencia_ao_emprestimo",
    ),
    path(
        "ocorrencias/cancelar/<int:pk>/",
        views.CancelarOcorrenciaView.as_view(),
        name="cancelar_ocorrencia",
    ),
    path(
        "emprestimo/atualizar_tabela_emprestimo/",
        views.atualizar_tabela_emprestimo_view,
        name="atualizar_tabela_emprestimo",
    ),
]

ensino/presentation/urls.py
from django.urls import path

from . import views


app_name = "ensino"

urlpatterns = [
    path(
        "campus/",
        views.ListarCampusView.as_view(),
        name="listar_campi",
    ),
    path(
        "campus/add",
        views.CriarCampusView.as_view(),
        name="criar_campus",
    ),
    path(
        "campus/change/<int:pk>/",
        views.EditarCampusView.as_view(),
        name="editar_campus",
    ),
    path(
        "campus/delete/<int:pk>/",
        views.remover_campus,
        name="remover_campus",
    ),
    path(
        "curso/",
        views.ListarCursoView.as_view(),
        name="listar_cursos",
    ),
    path(
        "curso/add",
        views.CriarCursoView.as_view(),
        name="criar_curso",
    ),
    path(
        "curso/change/<int:pk>/",
        views.EditarCursoView.as_view(),
        name="editar_curso",
    ),
    path(
        "curso/delete/<int:pk>/",
        views.remover_curso,
        name="remover_curso",
    ),
    path(
        "forma_selecao/",
        views.ListarFormaSelecaoView.as_view(),
        name="listar_formas_selecao",
    ),
    path(
        "forma_selecao/add",
        views.CriarFormaSelecaoView.as_view(),
        name="criar_forma_selecao",
    ),
    path(
        "forma_selecao/change/<int:pk>/",
        views.EditarFormaSelecaoView.as_view(),
        name="editar_forma_selecao",
    ),
    path(
        "forma_selecao/delete/<int:pk>/",
        views.remover_forma_selecao,
        name="remover_forma_selecao",
    ),
    path(
        "aluno/",
        views.ListarAlunoView.as_view(),
        name="listar_alunos",
    ),
    path(
        "aluno/add",
        views.CriarAlunoView.as_view(),
        name="criar_aluno",
    ),
    path(
        "aluno/change/<int:pk>/",
        views.EditarAlunoView.as_view(),
        name="editar_aluno",
    ),
    path(
        "aluno/delete/<int:pk>/",
        views.remover_aluno,
        name="remover_aluno",
    ),
]

inventory_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ativos/', include('ativos.urls')),
]

patrimonio/presentation/urls.py
from django.urls import path

from . import views


app_name = "patrimonio"
urlpatterns = [
    path(
        "tipo_bem/",
        views.ListarTiposBemView.as_view(),
        name="listar_tipos_bem",
    ),
    path(
        "tipo_bem/add",
        views.CriarTipoBemView.as_view(),
        name="criar_tipo_bem",
    ),
    path(
        "tipo_bem/change/<int:pk>/",
        views.EditarTipoBemView.as_view(),
        name="editar_tipo_bem",
    ),
    path(
        "tipo_bem/delete/<int:pk>/",
        views.remover_tipobem,
        name="remover_tipo_bem",
    ),
    path(
        "estado_conservacao/",
        views.ListarEstadosConservacaoView.as_view(),
        name="listar_estados_conservacao",
    ),
    path(
        "estado_conservacao/add",
        views.CriarEstadoConservacaoView.as_view(),
        name="criar_estado_conservacao",
    ),
    path(
        "estado_conservacao/change/<int:pk>/",
        views.EditarEstadoConservacaoView.as_view(),
        name="editar_estado_conservacao",
    ),
    path(
        "estado_conservacao/delete/<int:pk>/",
        views.remover_estado_conservacao,
        name="remover_estado_conservacao",
    ),
    path(
        "grau_fragilidade/",
        views.ListarGrauFragilidadeView.as_view(),
        name="listar_grau_fragilidade",
    ),
    path(
        "grau_fragilidade/add",
        views.CriarGrauFragilidadeView.as_view(),
        name="criar_grau_fragilidade",
    ),
    path(
        "grau_fragilidade/change/<int:pk>/",
        views.EditarGrauFragilidadeView.as_view(),
        name="editar_grau_fragilidade",
    ),
    path(
        "grau_fragilidade/delete/<int:pk>/",
        views.remover_grau_fragilidade,
        name="remover_grau_fragilidade",
    ),
    path(
        "marca_modelo/",
        views.ListarMarcaModeloView.as_view(),
        name="listar_marca_modelo",
    ),
    path(
        "marca_modelo/add",
        views.CriarMarcaModeloView.as_view(),
        name="criar_marca_modelo",
    ),
    path(
        "marca_modelo/change/<int:pk>/",
        views.EditarMarcaModeloView.as_view(),
        name="editar_marca_modelo",
    ),
    path(
        "marca_modelo/delete/<int:pk>/",
        views.remover_marca_modelo,
        name="remover_marca_modelo",
    ),
    path(
        "bem/",
        views.ListarBemView.as_view(),
        name="listar_bens",
    ),
    path(
        "bem/add",
        views.CriarBemView.as_view(),
        name="criar_bem",
    ),
    path(
        "bem/change/<int:pk>/",
        views.EditarBemView.as_view(),
        name="editar_bem",
    ),
    path(
        "bem/delete/<int:pk>/",
        views.remover_bem,
        name="remover_bem",
    ),
]

sigecomp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ativos/", include("ativos.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

sigemp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.presentation.views import model_autocomplete

urlpatterns = [
    path("", include("core.presentation.urls")),
    path("patrimonio/", include("patrimonio.presentation.urls")),
    path("ensino/", include("ensino.presentation.urls")),
    path("emprestimo/", include("emprestimo.presentation.urls")),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/reset_done.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "accounts/password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "autocomplete/",
        model_autocomplete,
        name="model_autocomplete",
    ),
]

emprestimo/models.py
from django.contrib.auth.models import User
from django.db import models

from core.models import Timestampable
from emprestimo.domain.types import EmprestimoEstadoEnum
from ensino.models import Aluno
from patrimonio.models import Bem


# Create your models here.
class TipoOcorrencia(Timestampable, models.Model):
    descricao = models.CharField(null=False, blank=False, max_length=255)

    def __str__(self) -> str:
        return f"{self.descricao}"


class Emprestimo(Timestampable, models.Model):
    data_emprestimo = models.DateField()
    data_devolucao_prevista = models.DateField()
    data_devolucao = models.DateField(null=True, blank=True)
    devolucao_ciente_por = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    bem = models.ForeignKey(
        Bem,
        on_delete=models.CASCADE,
    )
    aluno = models.ForeignKey(
        Aluno,
        on_delete=models.CASCADE,
    )
    estado = models.IntegerField(
        choices=EmprestimoEstadoEnum.choices(),
    )
    observacoes = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"#{self.id} ({self.get_estado_display()}): {self.aluno.nome} ({self.aluno.matricula}) - {self.bem.descricao} ({self.bem.patrimonio})"


class Ocorrencia(Timestampable, models.Model):
    data_ocorrencia = models.DateField()
    emprestimo = models.ForeignKey(Emprestimo, on_delete=models.CASCADE)
    tipo = models.ForeignKey(TipoOcorrencia, on_delete=models.CASCADE)
    descricao = models.TextField(null=True, blank=True)
    cancelado_em = models.DateField(null=True, blank=True)
    cancelado_por = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="ocorrencias_canceladas",
    )
    motivo_cancelamento = models.CharField(max_length=255, null=True, blank=True)

emprestimo/presentation/forms.py
from typing import Optional
from django import forms
from django.forms.widgets import DateInput

from core.widgets import ModelAutocompleteWidget
from emprestimo.domain.types import EmprestimoEstadoEnum
from emprestimo.models import Emprestimo, Ocorrencia, TipoOcorrencia
from ensino.models import Aluno
from patrimonio.models import Bem


class TipoOcorrenciaForm(forms.ModelForm):
    class Meta:
        model = TipoOcorrencia
        fields = ["descricao"]


class CriarEmprestimoForm(forms.ModelForm):
    data_emprestimo = forms.DateField(
        label="Data de retirada",
        widget=DateInput(attrs={"type": "date"}),
    )
    data_devolucao_prevista = forms.DateField(
        label="Data de devolução prevista",
        widget=DateInput(attrs={"type": "date"}),
    )

    aluno = forms.ModelChoiceField(
        Aluno.objects,
        widget=ModelAutocompleteWidget(Aluno),
    )

    bem = forms.ModelChoiceField(
        Bem.objects,
        widget=ModelAutocompleteWidget(Bem),
    )

    class Meta:
        model = Emprestimo
        fields = [
            "aluno",
            "bem",
            "data_emprestimo",
            "data_devolucao_prevista",
            "observacoes",
        ]


class OcorrenciaForm(forms.ModelForm):
    data_ocorrencia = forms.DateField(
        label="Data da ocorrência",
        widget=DateInput(attrs={"type": "date"}),
    )

    emprestimo = forms.ModelChoiceField(
        queryset=Emprestimo.objects.all().order_by("-data_emprestimo", "estado"),
        widget=ModelAutocompleteWidget(Emprestimo),
    )

    def __init__(self, *args, **kwargs) -> None:
        e: Optional[Emprestimo] = None

        if "emprestimo" in kwargs.keys():
            e = kwargs.pop("emprestimo")

        super().__init__(*args, **kwargs)

        if e:
            self.fields["emprestimo"].initial = e
            self.fields["emprestimo"].disabled = True

    class Meta:
        model = Ocorrencia
        fields = ["tipo", "emprestimo", "data_ocorrencia", "descricao"]


class CancelarOcorrenciaForm(forms.ModelForm):
    class Meta:
        model = Ocorrencia
        fields = ["motivo_cancelamento"]


class EmprestimoFilterForm(forms.Form):
    texto = forms.CharField(max_length=255, required=False)
    estado = forms.ChoiceField(
        choices=[(None, "---------")] + EmprestimoEstadoEnum.choices(),
        required=False,
    )
    tem_ocorrencia = forms.ChoiceField(
        label="Possui ocorrência?",
        required=False,
        choices=[("", "---------"), ("s", "Sim"), ("n", "Não")],
    )


class OcorrenciaFilterForm(forms.Form):
    aluno = forms.CharField(max_length=255, required=False)
    bem = forms.CharField(max_length=255, required=False)
    data_ocorrencia = forms.DateField(
        label="Data da ocorrência",
        required=False,
        widget=DateInput(attrs={"type": "date"}),
    )
    tipo = forms.ModelChoiceField(
        queryset=TipoOcorrencia.objects,
        required=False,
    )
    eh_cancelado = forms.ChoiceField(
        label="Cancelado?",
        required=False,
        choices=[("", "---------"), ("s", "Sim"), ("n", "Não")],
    )

emprestimo/templates/emprestimo/emprestimo/emprestimo_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block page_title %}
    {% if form.instance.id %}
        Editar {{ form.instance.nome }}
    {% else %}
        Cadastrar Empréstimo
    {% endif %}
{% endblock %}
{% block actions %}
    {% if form.instance.id %}
        <a href="{% url 'emprestimo:remover_tipo_ocorrencia' form.instance.id %}"
           class="cursor-pointer flex items-center gap-2 rounded-md border border-red-500 bg-red-50 px-4 py-2 text-sm font-semibold text-red-600 transition-all duration-300 ease-in-out hover:bg-red-100 hover:shadow-md hover:ring-2 hover:ring-red-300 dark:border-red-400 dark:bg-gray-800 dark:text-red-300 dark:hover:bg-gray-700 dark:hover:ring-red-500/40">
            <i class="material-symbols-outlined align-middle">delete</i>
            <span>Remover</span>
        </a>
    {% endif %}
{% endblock actions %}
{% block content %}
    <section class="mx-auto max-w-4xl gap-y-6 rounded-md bg-gray-50 p-6 text-gray-900 shadow-md dark:bg-gray-900 dark:text-white">
        <form method="post" class="grid grid-cols-1 gap-6 md:grid-cols-2">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="flex flex-col gap-2">
                    <div class="flex flex-row items-center">
                        <label class="text-sm font-semibold text-gray-800 dark:text-white"
                               for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {% if not field.field.required %}<span class="text-xs italic px-2 text-gray-400">(opcional)</span>{% endif %}
                        {% if field.errors %}
                            <div class="px-2 text-sm font-bold text-red-600 dark:text-red-400">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                    {% render_field field class="block w-full min-w-0 rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500" %}
                </div>
            {% endfor %}
            <div class="col-span-full mt-4">
                <button type="submit"
                        class="cursor-pointer flex items-center gap-2 rounded-md border border-blue-500 bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-600 transition-all duration-300 ease-in-out hover:bg-blue-100 hover:shadow-md hover:ring-2 hover:ring-blue-300 dark:border-blue-400 dark:bg-gray-800 dark:text-blue-300 dark:hover:bg-gray-700 dark:hover:ring-blue-500/40">
                    Salvar
                </button>
            </div>
        </form>
    </section>
{% endblock %}

emprestimo/templates/emprestimo/emprestimo/emprestimo_list.html
{% extends "base.html" %}
{% block page_title %}
    Empréstimos
{% endblock page_title %}
{% block actions %}
    {% if pode_criar %}
        <div class="flex justify-end md:justify-start">
            <a href="{% url 'emprestimo:criar_emprestimo' %}">
                <div class="rounded-md w-fit py-2 gap-2 flex px-4 border border-blue-500 text-blue-600 dark:border-blue-400 dark:text-blue-300 bg-blue-50 dark:bg-gray-800 items-center font-semibold text-sm transition-all duration-300 ease-in-out hover:bg-blue-100 dark:hover:bg-gray-700 hover:ring-2 hover:ring-blue-300 dark:hover:ring-blue-500/40 hover:shadow-md cursor-pointer">
                    <i class="material-symbols-outlined transition-transform duration-300 group-hover:rotate-6">add</i>
                    <span class="hidden md:block">Novo Empréstimo</span>
                </div>
            </a>
        </div>
    {% endif %}
{% endblock actions %}
{% block filter_form %}
    {% include "partials/filter_form.html" %}
{% endblock filter_form %}
{% block content %}
    <section class="bg-gray-50 dark:bg-gray-900 text-gray-500 dark:text-gray-300 max-w-7xl mx-auto p-2 shadow-md rounded-md">
        <div class="overflow-y-auto max-h-[calc(100vh-250px)]">
            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead class="bg-gray-50 dark:bg-gray-900 sticky top-0 border-b-2 border-solid  border-b-gray-200 dark:border-b-gray-700">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                            Ações
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                            Aluno
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Bem</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                            Data Empréstimo
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                            Data Devolução Prevista
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                            Data Devolução
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                            Status
                        </th>
                    </tr>
                </thead>
                <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
                    {% for emprestimo in emprestimos %}
                        <tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
                            <td class="px-6 py-4">
                                <div class="flex items-center gap-3">
                                    <a href="{% url 'emprestimo:editar_emprestimo' emprestimo.id %}"
                                       class="text-gray-500 hover:text-blue-600 transition-colors duration-200 dark:text-gray-400 dark:hover:text-blue-400"
                                       title="Editar empréstimo">
                                        <i class="material-symbols-outlined text-lg">edit</i>
                                    </a>
                                    <a href="{% url 'emprestimo:visualizar_emprestimo' emprestimo.id %}"
                                       class="text-gray-500 hover:text-green-600 transition-colors duration-200 dark:text-gray-400 dark:hover:text-green-400"
                                       title="Visualizar empréstimo">
                                        <i class="material-symbols-outlined text-lg">visibility</i>
                                    </a>
                                </div>
                            </td>
                            <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">
                                <a href="{% url 'ensino:editar_aluno' emprestimo.aluno_id %}"
                                   class="group hover:text-blue-600 dark:hover:text-blue-400">
                                    {{ emprestimo.aluno_nome }}
                                    <span class="text-gray-600 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-400">({{ emprestimo.aluno_matricula }})</span>
                                </a>
                            </td>
                            <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">
                                <a href="{% url 'patrimonio:editar_bem' emprestimo.bem_id %}"
                                   class="group hover:text-blue-600 dark:hover:text-blue-400">
                                    {{ emprestimo.bem_descricao }}
                                    <span class="text-gray-600 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-400">({{ emprestimo.bem_patrimonio }})</span>
                                </a>
                            </td>
                            <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">{{ emprestimo.data_emprestimo|date:"d/m/Y" }}</td>
                            <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">
                                {{ emprestimo.data_devolucao_prevista|date:"d/m/Y" }}
                            </td>
                            <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">
                                {% if emprestimo.data_devolucao %}
                                    {{ emprestimo.data_devolucao|date:"d/m/Y" }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td class="px-6 py-4 text-sm text-gray-900 dark:text-gray-100">
                                <span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium {% if emprestimo.estado == 1 %} bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300 {% elif emprestimo.estado == 2 %} bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300  {% else %} bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300 {% endif %}">
                                    {{ emprestimo.estado.label }}
                                </span>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="px-6 py-4 text-sm text-gray-500 dark:text-gray-400">Nenhum empréstimo encontrado.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% include "partials/pagination.html" %}
    </section>
{% endblock %}